from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path

from .moex_iss import derive_moex_secid
from .phase9 import default_phase9_pilot_universe


@dataclass(frozen=True)
class QuikConnectorBinding:
    contract_id: str
    class_code: str
    sec_code: str
    timeframe: str
    interval: int

    def to_dict(self) -> dict[str, object]:
        return {
            "contract_id": self.contract_id,
            "class_code": self.class_code,
            "sec_code": self.sec_code,
            "timeframe": self.timeframe,
            "interval": self.interval,
        }


@dataclass(frozen=True)
class Phase9QuikConnectorConfig:
    provider_id: str
    export_path: str
    poll_interval_ms: int
    bindings: tuple[QuikConnectorBinding, ...]
    session_timezone: str

    def __post_init__(self) -> None:
        if self.provider_id.strip() != "quik-live":
            raise ValueError("provider_id must be quik-live")
        if not self.export_path.strip():
            raise ValueError("export_path must be non-empty")
        if self.poll_interval_ms <= 0:
            raise ValueError("poll_interval_ms must be positive")
        if not self.bindings:
            raise ValueError("bindings must be non-empty")
        if not self.session_timezone.strip():
            raise ValueError("session_timezone must be non-empty")

    def to_dict(self) -> dict[str, object]:
        return {
            "provider_id": self.provider_id,
            "export_path": self.export_path,
            "poll_interval_ms": self.poll_interval_ms,
            "bindings": [item.to_dict() for item in self.bindings],
            "session_timezone": self.session_timezone,
        }


def default_phase9_quik_connector_config(
    *,
    export_path: str,
    class_code: str = "SPBFUT",
    poll_interval_ms: int = 1000,
) -> Phase9QuikConnectorConfig:
    pilot_universe = default_phase9_pilot_universe()
    timeframe = pilot_universe.timeframes[0]
    interval = 15 if timeframe == "15m" else 5 if timeframe == "5m" else 60
    bindings = tuple(
        QuikConnectorBinding(
            contract_id=contract_id,
            class_code=class_code,
            sec_code=derive_moex_secid(contract_id),
            timeframe=timeframe,
            interval=interval,
        )
        for contract_id in pilot_universe.contract_ids
    )
    return Phase9QuikConnectorConfig(
        provider_id="quik-live",
        export_path=export_path,
        poll_interval_ms=poll_interval_ms,
        bindings=bindings,
        session_timezone=pilot_universe.session_timezone,
    )


def _lua_string(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def render_phase9_quik_lua_script(config: Phase9QuikConnectorConfig) -> str:
    bindings_rows = ",\n".join(
        [
            "    { contract_id = "
            + _lua_string(item.contract_id)
            + ", class_code = "
            + _lua_string(item.class_code)
            + ", sec_code = "
            + _lua_string(item.sec_code)
            + ", timeframe = "
            + _lua_string(item.timeframe)
            + ", interval = "
            + str(item.interval)
            + " }"
            for item in config.bindings
        ]
    )
    return f"""-- Auto-generated by scripts/build_phase9_quik_connector.py
local CONFIG = {{
  provider_id = {_lua_string(config.provider_id)},
  export_path = {_lua_string(config.export_path)},
  poll_interval_ms = {config.poll_interval_ms},
  bindings = {{
{bindings_rows}
  }}
}}

local is_running = true
local data_sources = {{}}

local function json_escape(value)
  local escaped = string.gsub(value, "\\\\", "\\\\\\\\")
  escaped = string.gsub(escaped, '"', '\\\\\\"')
  escaped = string.gsub(escaped, "\\n", "\\\\n")
  escaped = string.gsub(escaped, "\\r", "\\\\r")
  escaped = string.gsub(escaped, "\\t", "\\\\t")
  return escaped
end

local function json_string(value)
  return '"' .. json_escape(tostring(value)) .. '"'
end

local function json_number(value)
  if value == nil then
    return "null"
  end
  return tostring(value)
end

local function now_utc_iso()
  local t = os.date("!*t")
  return string.format("%04d-%02d-%02dT%02d:%02d:%02dZ", t.year, t.month, t.day, t.hour, t.min, t.sec)
end

local function parse_number(value)
  if value == nil then
    return nil
  end
  local text = tostring(value)
  text = string.gsub(text, ",", ".")
  return tonumber(text)
end

local function get_last_price(binding, ds)
  local ok, quote = pcall(getParamEx, binding.class_code, binding.sec_code, "LAST")
  if ok and type(quote) == "table" then
    local parsed = parse_number(quote.param_value or quote.value or quote.param_image)
    if parsed ~= nil and parsed > 0 then
      return parsed
    end
  end
  if ds == nil then
    return nil
  end
  local size = ds:Size()
  if size <= 0 then
    return nil
  end
  local ok_close, close_value = pcall(function() return ds:C(size) end)
  if ok_close and type(close_value) == "number" then
    return close_value
  end
  return nil
end

local function encode_rows(rows)
  local chunks = {{}}
  for index, row in ipairs(rows) do
    local encoded = "{{" ..
      '"contract_id":' .. json_string(row.contract_id) .. "," ..
      '"event_ts":' .. json_string(row.event_ts) .. "," ..
      '"session_state":' .. json_string(row.session_state) .. "," ..
      '"last_price":' .. json_number(row.last_price) .. "," ..
      '"class_code":' .. json_string(row.class_code) .. "," ..
      '"sec_code":' .. json_string(row.sec_code) .. "," ..
      '"timeframe":' .. json_string(row.timeframe) ..
      "}}"
    chunks[#chunks + 1] = encoded
  end
  return "[" .. table.concat(chunks, ",") .. "]"
end

local function write_snapshot(rows)
  local payload = "{{" ..
    '"provider_id":' .. json_string(CONFIG.provider_id) .. "," ..
    '"rows":' .. encode_rows(rows) ..
    "}}"
  local temp_path = CONFIG.export_path .. ".tmp"
  local file = assert(io.open(temp_path, "w"))
  file:write(payload)
  file:close()
  os.remove(CONFIG.export_path)
  assert(os.rename(temp_path, CONFIG.export_path))
end

local function ensure_data_sources()
  for _, binding in ipairs(CONFIG.bindings) do
    if data_sources[binding.contract_id] == nil then
      local ds, err = CreateDataSource(binding.class_code, binding.sec_code, binding.interval)
      if ds == nil then
        error("CreateDataSource failed for " .. binding.contract_id .. ": " .. tostring(err))
      end
      data_sources[binding.contract_id] = ds
    end
  end
end

function OnStop()
  is_running = false
  for _, ds in pairs(data_sources) do
    pcall(function() ds:Close() end)
  end
end

function main()
  ensure_data_sources()
  while is_running do
    local rows = {{}}
    local now_ts = now_utc_iso()
    for _, binding in ipairs(CONFIG.bindings) do
      local ds = data_sources[binding.contract_id]
      rows[#rows + 1] = {{
        contract_id = binding.contract_id,
        event_ts = now_ts,
        session_state = "open",
        last_price = get_last_price(binding, ds),
        class_code = binding.class_code,
        sec_code = binding.sec_code,
        timeframe = binding.timeframe
      }}
    end
    local ok, err = pcall(function() write_snapshot(rows) end)
    if not ok then
      message("Phase9 QUIK export error: " .. tostring(err), 3)
    end
    sleep(CONFIG.poll_interval_ms)
  end
end
"""


def write_phase9_quik_connector_bundle(
    *,
    script_path: Path,
    config_path: Path,
    config: Phase9QuikConnectorConfig,
) -> None:
    script_path.parent.mkdir(parents=True, exist_ok=True)
    config_path.parent.mkdir(parents=True, exist_ok=True)
    script_path.write_text(render_phase9_quik_lua_script(config), encoding="utf-8")
    config_path.write_text(json.dumps(config.to_dict(), ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
