from __future__ import annotations

"""Harness foundation package for phase-driven local orchestration."""

from .models import (
    ArtifactManifestEntry,
    ArtifactManifestEntryModel,
    DocExcerpt,
    DocExcerptModel,
    DomainGlossaryEntry,
    DomainGlossaryEntryModel,
    NormalizedRequirement,
    NormalizedRequirementModel,
    PhaseContext,
    PhaseContextModel,
    PhaseDefinition,
    PhaseDefinitionModel,
    PhasePlanModel,
    PriorFinding,
    PriorFindingModel,
    ProjectDocsBundle,
    ProjectDocsBundleModel,
    RiskRegisterEntry,
    RiskRegisterEntryModel,
    RunState,
    RunStateModel,
    SpecManifestModel,
    parse_normalized_requirements,
    parse_phase_context,
    parse_phase_plan,
    parse_project_docs_bundle,
    parse_run_state,
    parse_spec_manifest,
)
from .schema_registry import LoadedSchema, SchemaValidationError, load_schema_catalog, resolve_schema_dir

__all__ = [
    "ArtifactManifestEntry",
    "ArtifactManifestEntryModel",
    "DocExcerpt",
    "DocExcerptModel",
    "DomainGlossaryEntry",
    "DomainGlossaryEntryModel",
    "LoadedSchema",
    "NormalizedRequirement",
    "NormalizedRequirementModel",
    "PhaseContext",
    "PhaseContextModel",
    "PhaseDefinition",
    "PhaseDefinitionModel",
    "PhasePlanModel",
    "PriorFinding",
    "PriorFindingModel",
    "ProjectDocsBundle",
    "ProjectDocsBundleModel",
    "RiskRegisterEntry",
    "RiskRegisterEntryModel",
    "RunState",
    "RunStateModel",
    "SchemaValidationError",
    "SpecManifestModel",
    "load_schema_catalog",
    "parse_normalized_requirements",
    "parse_phase_context",
    "parse_phase_plan",
    "parse_project_docs_bundle",
    "parse_run_state",
    "parse_spec_manifest",
    "resolve_schema_dir",
]
