from __future__ import annotations


def historical_data_delta_schema_manifest() -> dict[str, dict[str, object]]:
    return {
        "raw_market_backfill": {
            "format": "delta",
            "partition_by": ["contract_id", "timeframe"],
            "columns": {
                "contract_id": "string",
                "instrument_id": "string",
                "timeframe": "string",
                "ts_open": "timestamp",
                "ts_close": "timestamp",
                "open": "double",
                "high": "double",
                "low": "double",
                "close": "double",
                "volume": "bigint",
                "open_interest": "bigint",
            },
        },
        "raw_moex_session_schedule": {
            "format": "delta",
            "partition_by": ["engine", "market", "board", "trade_date"],
            "constraints": [
                "non_empty(source_id)",
                "non_empty(source_url)",
                "non_empty(source_document_hash)",
            ],
            "columns": {
                "source_id": "string",
                "source_url": "string",
                "source_document_id": "string",
                "source_document_hash": "string",
                "fetched_at_utc": "timestamp",
                "engine": "string",
                "market": "string",
                "board": "string",
                "moex_secid": "string",
                "trade_date": "date",
                "raw_payload_json": "string",
            },
        },
        "canonical_session_intervals": {
            "format": "delta",
            "partition_by": ["instrument_id", "session_date"],
            "constraints": [
                "unique(instrument_id, session_date, interval_id)",
                "non_empty(source_id)",
                "non_empty(source_document_hash)",
                "expected_open_ts < expected_close_ts",
            ],
            "columns": {
                "instrument_id": "string",
                "session_date": "date",
                "interval_id": "string",
                "interval_seq": "int",
                "expected_open_ts": "timestamp",
                "expected_close_ts": "timestamp",
                "session_class": "string",
                "interval_type": "string",
                "policy_id": "string",
                "source_id": "string",
                "source_document_hash": "string",
            },
        },
        "canonical_bars": {
            "format": "delta",
            "partition_by": ["contract_id", "timeframe"],
            "constraints": ["unique(contract_id, timeframe, ts)"],
            "columns": {
                "contract_id": "string",
                "instrument_id": "string",
                "timeframe": "string",
                "ts": "timestamp",
                "open": "double",
                "high": "double",
                "low": "double",
                "close": "double",
                "volume": "bigint",
                "open_interest": "bigint",
            },
        },
        "canonical_bar_provenance": {
            "format": "delta",
            "partition_by": ["contract_id", "timeframe"],
            "constraints": ["unique(contract_id, timeframe, ts)"],
            "columns": {
                "contract_id": "string",
                "instrument_id": "string",
                "timeframe": "string",
                "ts": "timestamp",
                "bar_start_ts": "timestamp",
                "bar_end_ts": "timestamp",
                "session_interval_id": "string",
                "source_provider": "string",
                "source_timeframe": "string",
                "source_interval": "int",
                "source_run_id": "string",
                "source_ingest_run_id": "string",
                "source_row_count": "bigint",
                "source_ts_open_first": "timestamp",
                "source_ts_close_last": "timestamp",
                "open_interest_imputed": "boolean",
                "build_run_id": "string",
                "built_at_utc": "timestamp",
            },
        },
        "canonical_instruments": {
            "format": "delta",
            "partition_by": [],
            "constraints": ["unique(instrument_id)"],
            "columns": {
                "instrument_id": "string",
            },
        },
        "canonical_contracts": {
            "format": "delta",
            "partition_by": ["instrument_id"],
            "constraints": ["unique(contract_id)"],
            "columns": {
                "contract_id": "string",
                "instrument_id": "string",
                "first_seen_ts": "timestamp",
                "last_seen_ts": "timestamp",
            },
        },
        "canonical_session_calendar": {
            "format": "delta",
            "partition_by": ["instrument_id", "session_date"],
            "constraints": ["unique(instrument_id, timeframe, session_date)"],
            "columns": {
                "instrument_id": "string",
                "timeframe": "string",
                "session_date": "date",
                "session_open_ts": "timestamp",
                "session_close_ts": "timestamp",
                "session_class": "string",
            },
        },
        "canonical_roll_map": {
            "format": "delta",
            "partition_by": ["instrument_id", "session_date"],
            "constraints": ["unique(instrument_id, session_date)"],
            "columns": {
                "instrument_id": "string",
                "session_date": "date",
                "active_contract_id": "string",
                "reason": "string",
            },
        },
    }
