from __future__ import annotations


def historical_data_delta_schema_manifest() -> dict[str, dict[str, object]]:
    return {
        "raw_market_backfill": {
            "format": "delta",
            "partition_by": ["contract_id", "timeframe"],
            "columns": {
                "contract_id": "string",
                "instrument_id": "string",
                "timeframe": "string",
                "ts_open": "timestamp",
                "ts_close": "timestamp",
                "open": "double",
                "high": "double",
                "low": "double",
                "close": "double",
                "volume": "bigint",
                "open_interest": "bigint",
            },
        },
        "raw_moex_session_schedule": {
            "format": "delta",
            "partition_by": ["engine", "market", "board", "trade_date"],
            "constraints": [
                "non_empty(source_id)",
                "non_empty(source_url)",
                "non_empty(source_document_hash)",
            ],
            "columns": {
                "source_id": "string",
                "source_url": "string",
                "source_document_id": "string",
                "source_document_hash": "string",
                "fetched_at_utc": "timestamp",
                "engine": "string",
                "market": "string",
                "board": "string",
                "moex_secid": "string",
                "trade_date": "date",
                "raw_payload_json": "string",
            },
        },
        "raw_moex_history": {
            "format": "delta",
            "partition_by": ["ts_close_year"],
            "constraints": [
                "unique(internal_id, timeframe, moex_secid, ts_open, ts_close)",
                "non_empty(internal_id)",
                "non_empty(moex_secid)",
                "ts_open <= ts_close",
            ],
            "columns": {
                "internal_id": "string",
                "finam_symbol": "string",
                "moex_engine": "string",
                "moex_market": "string",
                "moex_board": "string",
                "moex_secid": "string",
                "asset_group": "string",
                "timeframe": "string",
                "source_interval": "int",
                "ts_open": "timestamp",
                "ts_close": "timestamp",
                "open": "double",
                "high": "double",
                "low": "double",
                "close": "double",
                "volume": "bigint",
                "open_interest": "bigint",
                "ingest_run_id": "string",
                "ingested_at_utc": "timestamp",
                "provenance_json": "json",
                "ts_close_year": "int",
            },
        },
        "raw_moex_contract_securities": {
            "format": "delta",
            "partition_by": ["engine", "market", "board", "trade_date"],
            "constraints": [
                "non_empty(source_id)",
                "non_empty(source_url)",
                "non_empty(source_document_hash)",
                "non_empty(moex_secid)",
            ],
            "columns": {
                "source_id": "string",
                "source_url": "string",
                "source_document_id": "string",
                "source_document_hash": "string",
                "fetched_at_utc": "timestamp",
                "engine": "string",
                "market": "string",
                "board": "string",
                "moex_secid": "string",
                "trade_date": "date",
                "assetcode": "string",
                "contract_shortname": "string",
                "last_trade_date": "date",
                "last_del_date": "date",
                "min_step": "double",
                "lot_volume": "double",
                "official_step_price": "double",
                "official_initial_margin": "double",
                "last_settle_price": "double",
                "raw_payload_json": "string",
            },
        },
        "raw_moex_indicative_fx_rates": {
            "format": "delta",
            "partition_by": ["trade_date", "clearing_type"],
            "constraints": [
                "non_empty(source_id)",
                "non_empty(source_url)",
                "non_empty(source_document_hash)",
                "non_empty(fx_pair)",
            ],
            "columns": {
                "source_id": "string",
                "source_url": "string",
                "source_document_id": "string",
                "source_document_hash": "string",
                "fetched_at_utc": "timestamp",
                "trade_date": "date",
                "trade_time": "string",
                "fx_pair": "string",
                "clearing_type": "string",
                "rate": "double",
                "raw_payload_json": "string",
            },
        },
        "raw_moex_rms_limits": {
            "format": "delta",
            "partition_by": ["trade_date"],
            "constraints": [
                "non_empty(source_id)",
                "non_empty(source_url)",
                "non_empty(source_document_hash)",
                "non_empty(assetcode)",
            ],
            "columns": {
                "source_id": "string",
                "source_url": "string",
                "source_document_id": "string",
                "source_document_hash": "string",
                "fetched_at_utc": "timestamp",
                "trade_date": "date",
                "assetcode": "string",
                "mr1": "double",
                "mr2": "double",
                "mr3": "double",
                "lk1": "double",
                "lk2": "double",
                "title": "string",
                "group_title": "string",
                "update_time": "timestamp",
                "raw_payload_json": "string",
            },
        },
        "raw_moex_rms_staticparams": {
            "format": "delta",
            "partition_by": ["trade_date"],
            "constraints": [
                "non_empty(source_id)",
                "non_empty(source_url)",
                "non_empty(source_document_hash)",
                "non_empty(assetcode)",
            ],
            "columns": {
                "source_id": "string",
                "source_url": "string",
                "source_document_id": "string",
                "source_document_hash": "string",
                "fetched_at_utc": "timestamp",
                "trade_date": "date",
                "assetcode": "string",
                "radius_pct": "double",
                "update_time": "timestamp",
                "raw_payload_json": "string",
            },
        },
        "canonical_session_intervals": {
            "format": "delta",
            "partition_by": [],
            "target_file_count": 1,
            "constraints": [
                "unique(instrument_id, session_date, interval_id)",
                "non_empty(source_id)",
                "non_empty(source_document_hash)",
                "expected_open_ts < expected_close_ts",
            ],
            "columns": {
                "instrument_id": "string",
                "session_date": "date",
                "interval_id": "string",
                "interval_seq": "int",
                "expected_open_ts": "timestamp",
                "expected_close_ts": "timestamp",
                "session_class": "string",
                "interval_type": "string",
                "policy_id": "string",
                "source_id": "string",
                "source_document_hash": "string",
            },
        },
        "canonical_bars": {
            "format": "delta",
            "partition_by": [],
            "target_file_count": 16,
            "constraints": ["unique(contract_id, timeframe, ts)"],
            "columns": {
                "contract_id": "string",
                "instrument_id": "string",
                "timeframe": "string",
                "ts": "timestamp",
                "open": "double",
                "high": "double",
                "low": "double",
                "close": "double",
                "volume": "bigint",
                "open_interest": "bigint",
            },
        },
        "canonical_bar_provenance": {
            "format": "delta",
            "partition_by": [],
            "target_file_count": 16,
            "constraints": ["unique(contract_id, timeframe, ts)"],
            "columns": {
                "contract_id": "string",
                "instrument_id": "string",
                "timeframe": "string",
                "ts": "timestamp",
                "bar_start_ts": "timestamp",
                "bar_end_ts": "timestamp",
                "session_interval_id": "string",
                "source_provider": "string",
                "source_timeframe": "string",
                "source_interval": "int",
                "source_run_id": "string",
                "source_ingest_run_id": "string",
                "source_row_count": "int",
                "source_ts_open_first": "timestamp",
                "source_ts_close_last": "timestamp",
                "open_interest_imputed": "int",
                "build_run_id": "string",
                "built_at_utc": "timestamp",
            },
        },
        "canonical_instruments": {
            "format": "delta",
            "partition_by": [],
            "constraints": ["unique(instrument_id)"],
            "columns": {
                "instrument_id": "string",
            },
        },
        "canonical_contracts": {
            "format": "delta",
            "partition_by": ["instrument_id"],
            "constraints": ["unique(contract_id)"],
            "columns": {
                "contract_id": "string",
                "instrument_id": "string",
                "first_seen_ts": "timestamp",
                "last_seen_ts": "timestamp",
            },
        },
        "canonical_session_calendar": {
            "format": "delta",
            "partition_by": [],
            "target_file_count": 1,
            "constraints": ["unique(instrument_id, timeframe, session_date)"],
            "columns": {
                "instrument_id": "string",
                "timeframe": "string",
                "session_date": "date",
                "session_open_ts": "timestamp",
                "session_close_ts": "timestamp",
                "session_class": "string",
            },
        },
        "canonical_roll_map": {
            "format": "delta",
            "partition_by": [],
            "target_file_count": 1,
            "constraints": ["unique(instrument_id, session_date)"],
            "columns": {
                "instrument_id": "string",
                "session_date": "date",
                "active_contract_id": "string",
                "reason": "string",
            },
        },
        "canonical_fx_rates": {
            "format": "delta",
            "partition_by": [],
            "target_file_count": 1,
            "constraints": ["unique(rate_date, fx_pair, clearing_type)"],
            "columns": {
                "rate_date": "date",
                "fx_pair": "string",
                "base_currency": "string",
                "quote_currency": "string",
                "clearing_type": "string",
                "rate_to_rub": "double",
                "source_id": "string",
                "source_document_hash": "string",
                "model_version": "string",
                "created_at": "timestamp",
            },
        },
        "canonical_asset_risk_parameters": {
            "format": "delta",
            "partition_by": [],
            "target_file_count": 1,
            "constraints": ["unique(assetcode, risk_session_date)"],
            "columns": {
                "assetcode": "string",
                "risk_session_date": "date",
                "mr1": "double",
                "mr2": "double",
                "mr3": "double",
                "radius_pct": "double",
                "radius_source": "string",
                "source_limits_hash": "string",
                "source_staticparams_hash": "string",
                "model_version": "string",
                "created_at": "timestamp",
            },
        },
        "canonical_contract_economics": {
            "format": "delta",
            "partition_by": [],
            "target_file_count": 1,
            "constraints": ["unique(contract_id, economics_session_date, clearing_type)"],
            "columns": {
                "contract_id": "string",
                "instrument_id": "string",
                "moex_secid": "string",
                "assetcode": "string",
                "economics_session_date": "date",
                "effective_session_date": "date",
                "clearing_type": "string",
                "effective_from_ts": "timestamp",
                "effective_to_ts": "timestamp",
                "min_step": "double",
                "lot_volume": "double",
                "quote_currency": "string",
                "fx_rate_to_rub": "double",
                "tick_value_currency": "double",
                "step_price_rub": "double",
                "official_step_price": "double",
                "official_initial_margin": "double",
                "last_settle_price": "double",
                "mr1": "double",
                "radius_pct": "double",
                "radius_source": "string",
                "margin_formula_base": "double",
                "margin_radius_adjusted": "double",
                "margin_required_no_buffer": "double",
                "margin_buffer_pct": "double",
                "margin_required_estimate": "double",
                "maturity_rank": "int",
                "days_to_expiry": "int",
                "expiration_date": "date",
                "model_version": "string",
                "buffer_policy_version": "string",
                "model_quality": "string",
                "source_flags_json": "json",
                "source_document_hashes_json": "json",
                "created_at": "timestamp",
            },
        },
    }
