from __future__ import annotations

from trading_advisor_3000.product_plane.research.derived_indicators.registry import (
    DerivedIndicatorProfile,
    current_derived_indicator_profile,
)
from trading_advisor_3000.product_plane.research.indicators.registry import (
    IndicatorProfile,
    default_indicator_profile,
)


CF_INDICATOR_TABLES = (
    "cf_indicator_input_frame",
    "indicator_roll_rules",
    "continuous_front_indicator_frames",
    "continuous_front_derived_indicator_frames",
    "continuous_front_indicator_qc_observations",
    "continuous_front_indicator_run_manifest",
    "continuous_front_indicator_acceptance_report",
)


def _indicator_value_columns(profile: IndicatorProfile | None = None) -> dict[str, str]:
    resolved = profile or default_indicator_profile()
    return {column: "double" for column in resolved.expected_output_columns()}


def _derived_value_columns(profile: DerivedIndicatorProfile | None = None) -> dict[str, str]:
    resolved = profile or current_derived_indicator_profile()
    return {
        column: "int" if column.endswith("_code") or column.endswith("_flag") else "double"
        for column in resolved.output_columns
    }


def continuous_front_indicator_store_contract(
    *,
    indicator_profile: IndicatorProfile | None = None,
    derived_profile: DerivedIndicatorProfile | None = None,
) -> dict[str, dict[str, object]]:
    return {
        "cf_indicator_input_frame": {
            "format": "delta",
            "partition_by": [
                "dataset_version",
                "roll_policy_version",
                "adjustment_policy_version",
                "instrument_id",
                "timeframe",
            ],
            "constraints": [
                "unique(dataset_version, roll_policy_version, adjustment_policy_version, instrument_id, timeframe, ts)"
            ],
            "columns": {
                "dataset_version": "string",
                "source_canonical_version": "string",
                "roll_policy_version": "string",
                "adjustment_policy_version": "string",
                "instrument_id": "string",
                "timeframe": "string",
                "ts": "timestamp",
                "ts_close": "timestamp",
                "session_date": "date",
                "session_open_ts": "timestamp",
                "session_close_ts": "timestamp",
                "active_contract_id": "string",
                "roll_epoch_id": "string",
                "roll_seq": "int",
                "is_roll_bar": "boolean",
                "is_first_bar_after_roll": "boolean",
                "bars_since_roll": "int",
                "native_open": "double",
                "native_high": "double",
                "native_low": "double",
                "native_close": "double",
                "native_volume": "bigint",
                "native_open_interest": "bigint",
                "cumulative_additive_offset": "double",
                "open0": "double",
                "high0": "double",
                "low0": "double",
                "close0": "double",
                "hl2_0": "double",
                "hlc3_0": "double",
                "true_range0": "double",
                "price_space_native": "string",
                "price_space_normalized": "string",
                "causality_watermark_ts": "timestamp",
                "input_front_row_hash": "string",
                "created_at_utc": "timestamp",
            },
        },
        "indicator_roll_rules": {
            "format": "delta",
            "partition_by": ["rule_set_version", "output_family"],
            "constraints": ["unique(rule_set_version, output_column)"],
            "columns": {
                "rule_set_version": "string",
                "indicator_id": "string",
                "output_column": "string",
                "output_family": "string",
                "formula_id": "string",
                "calculation_group_id": "string",
                "calculation_group_description": "string",
                "roll_class": "string",
                "input_price_space": "string",
                "output_price_space": "string",
                "state_space": "string",
                "adapter_id": "string",
                "adapter_version": "string",
                "adapter_input_columns": "array<string>",
                "adapter_output_columns": "array<string>",
                "pandas_ta_allowed": "boolean",
                "state_transform_on_roll": "string",
                "contract_boundary_policy": "string",
                "allow_cross_contract_window": "boolean",
                "reset_on_roll": "boolean",
                "anchor_sensitive": "boolean",
                "warmup_bars": "int",
                "requires_base_columns": "array<string>",
                "requires_input_columns": "array<string>",
                "causal_safe": "boolean",
                "notes": "string",
                "rule_hash": "string",
                "created_at_utc": "timestamp",
            },
        },
        "continuous_front_indicator_frames": {
            "format": "delta",
            "partition_by": [
                "dataset_version",
                "roll_policy_version",
                "adjustment_policy_version",
                "indicator_set_version",
                "rule_set_version",
                "instrument_id",
                "timeframe",
            ],
            "constraints": [
                "unique(dataset_version, roll_policy_version, adjustment_policy_version, indicator_set_version, rule_set_version, instrument_id, timeframe, ts)"
            ],
            "columns": {
                "dataset_version": "string",
                "roll_policy_version": "string",
                "adjustment_policy_version": "string",
                "indicator_set_version": "string",
                "rule_set_version": "string",
                "instrument_id": "string",
                "timeframe": "string",
                "ts": "timestamp",
                "ts_close": "timestamp",
                "session_date": "date",
                "active_contract_id": "string",
                "roll_epoch_id": "string",
                "roll_seq": "int",
                "cumulative_additive_offset": "double",
                "source_input_row_hash": "string",
                "indicator_row_hash": "string",
                "adapter_bundle_hash": "string",
                "cross_contract_window_any": "boolean",
                **_indicator_value_columns(indicator_profile),
                "created_at_utc": "timestamp",
            },
        },
        "continuous_front_derived_indicator_frames": {
            "format": "delta",
            "partition_by": [
                "dataset_version",
                "roll_policy_version",
                "adjustment_policy_version",
                "indicator_set_version",
                "derived_set_version",
                "rule_set_version",
                "instrument_id",
                "timeframe",
            ],
            "constraints": [
                "unique(dataset_version, roll_policy_version, adjustment_policy_version, indicator_set_version, derived_set_version, rule_set_version, instrument_id, timeframe, ts)"
            ],
            "columns": {
                "dataset_version": "string",
                "roll_policy_version": "string",
                "adjustment_policy_version": "string",
                "indicator_set_version": "string",
                "derived_set_version": "string",
                "rule_set_version": "string",
                "instrument_id": "string",
                "timeframe": "string",
                "ts": "timestamp",
                "ts_close": "timestamp",
                "session_date": "date",
                "active_contract_id": "string",
                "roll_epoch_id": "string",
                "roll_seq": "int",
                "cumulative_additive_offset": "double",
                "source_input_row_hash": "string",
                "source_base_indicator_row_hash": "string",
                "derived_row_hash": "string",
                "adapter_bundle_hash": "string",
                "cross_contract_window_any": "boolean",
                **_derived_value_columns(derived_profile),
                "created_at_utc": "timestamp",
            },
        },
        "continuous_front_indicator_qc_observations": {
            "format": "delta",
            "partition_by": ["run_id", "check_group"],
            "constraints": ["unique(run_id, check_id, entity_key)"],
            "columns": {
                "run_id": "string",
                "check_id": "string",
                "check_group": "string",
                "severity": "string",
                "status": "string",
                "entity_key": "string",
                "observed_value": "string",
                "expected_value": "string",
                "sample_rows_hash": "string",
                "sample_rows_json": "json",
                "created_at_utc": "timestamp",
            },
        },
        "continuous_front_indicator_run_manifest": {
            "format": "delta",
            "partition_by": ["dataset_version", "run_id"],
            "constraints": ["unique(run_id)"],
            "columns": {
                "run_id": "string",
                "dataset_version": "string",
                "roll_policy_version": "string",
                "adjustment_policy_version": "string",
                "indicator_set_version": "string",
                "derived_set_version": "string",
                "rule_set_version": "string",
                "input_delta_versions_json": "json",
                "input_delta_versions_hash": "string",
                "output_delta_versions_json": "json",
                "output_delta_versions_hash": "string",
                "rule_set_hash": "string",
                "adapter_bundle_hash": "string",
                "formula_kernel_hash": "string",
                "job_config_hash": "string",
                "spark_app_id": "string",
                "spark_event_log_path": "string",
                "calculation_app_id": "string",
                "calculation_event_log_path": "string",
                "code_artifact_hash": "string",
                "dependency_lock_hash": "string",
                "container_image_digest": "string",
                "created_by_pipeline": "string",
                "calculation_engines_json": "json",
                "publish_status": "string",
                "created_at_utc": "timestamp",
            },
        },
        "continuous_front_indicator_acceptance_report": {
            "format": "delta",
            "partition_by": ["dataset_version", "run_id"],
            "constraints": ["unique(run_id)"],
            "columns": {
                "run_id": "string",
                "dataset_version": "string",
                "rule_set_version": "string",
                "blocker_fail_count": "int",
                "schema_fail_count": "int",
                "adapter_authorization_fail_count": "int",
                "prefix_invariance_fail_count": "int",
                "formula_sample_fail_count": "int",
                "pandas_ta_parity_fail_count": "int",
                "lineage_fail_count": "int",
                "publish_status": "string",
                "created_at_utc": "timestamp",
            },
        },
    }
